services:
  - type: web
    name: famofire
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: ADMIN_KEY
        value: cbedf0fae5e7eb31444544a99f5277e3